### ISSUE TITLE
Translation notes

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/reading-ios-intro-to-xcode#11]
# Notes

  * translate mentions of obj-c to swift
  * Include a super super simple project that is complete with tests for them
    to play with
  * find and replace for `nslog` with `print`

**Comment by AnnJohn** [comment]
yes, also @JimCampagno do you think we should make a copy of this repo and use that for the Swift course? its not a sustainable plan long-term, but having a separate XCode lesson for the Swift course makes it easier for us to make changes that won't affect other curricula. With that said:

-- Can we set up the context just a little instead of diving right into "Xcode is the Integrated Development Environment (IDE) provided by Apple to third-party programmers such as yourself for developing iOS and OS X applications written in Objective-C and Swift. " i.e pose a question? Explain the why of this first.

**Comment by JimCampagno** [comment]
@AnnJohn Like usual, agree with all of that.

I currently have it marked as review where I plan on going at this with a scalpel and making it very useful, clear, where a student will know exactly what it is they NEED to know and most importantly WHY we're telling them this.

This will also be a separate repo so that way we can keep Swift separate from the rest of the other stuff.

**Comment by markedwardmurray** [comment]
FWIW i think you guys should really start off using Playgrounds instead of full Xcode projects. Leverage their simplicity for teaching the very basics of Swift, and wait until functions to introduce Xcode itself.
